[imagetransformation]
# usually debuffs are shown in the second row in the upper left corner 
# for a resolution I have found to use a width of 550x200 px work the best.
# width * height is the number of pixels to be observed, with the top left corner being the origin.
width=550
height=200
color_type="color" # currently only uses color_methd, color. Grayscale leads to false positives

# If remove_debuff=true then there must be a file debuffname.png in \resources\debuff_templates
[ailment]
	[ailment.shock]
	type="shock"
	key="3"
	remove_debuff=true
	
	[ailment.ignite]
	type="ignite"
	key=""
	remove_debuff=false
	
	[ailment.chill]
	type="chill"
	key=""
	remove_debuff=false
	
	[ailment.freeze]
	type="freeze"
	key="5"
	remove_debuff=true
	
	[ailment.bleed]
	type="bleed"
	key="1"
	remove_debuff=true
	
	[ailment.corrupting_blood]
	type="corrupting_blood"
	key="1"
	remove_debuff=true
	
	[ailment.poison]
	type="poison"
	key="2"
	remove_debuff=true


[curse]
	[curse.elemental_weakness]
	type="elemental_weakness"
	key=""
	remove_debuff=false
	
	[curse.enfeeble]
	type="enfeeble"
	key=""
	remove_debuff=false
	
	[curse.flamability]
	type="flamability"
	key=""
	remove_debuff=false
	
	[curse.snipers_mark]
	type="snipers_mark"
	key=""
	remove_debuff=false
	
	[curse.temporal_chains]
	type="temporal_chains"
	key=""
	remove_debuff=false


[ground]
	[curse.burning_ground]
	type="burning_ground"
	key=""
	remove_debuff=false
